name: ditonton
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  http: ^1.1.0
  provider: ^6.0.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  google_fonts: ^5.1.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.2.3
  get_it: ^7.6.0
  sqflite: ^2.3.0
  path_provider: ^2.1.0

dev_dependencies:
  mockito: ^5.4.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/