name: ditonton
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  bloc_test: ^9.1.4
  build_runner: ^2.4.6

  core:
    path: core
  movies:
    path: movies
  tvseries:
    path: tvseries

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - certificates/