name: story_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.1
  http: ^1.1.0
  get_it: ^7.6.0
  intl: ^0.18.0
  app_settings: ^5.0.0
  image_picker: ^1.0.1
  google_maps_flutter: ^2.4.0
  location: ^5.0.1
  geocoding: ^2.1.0
  flutter_image_compress: ^2.0.4
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true