name: tvseries
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  http: ^1.1.0
  dartz: ^0.10.1
  cached_network_image: ^3.2.3
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.1
  equatable: ^2.0.5
  rxdart: ^0.27.7
  bloc_test: ^9.1.4
  build_runner: ^2.4.6

  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  mockito: ^5.4.2
  test_cov_console: ^0.2.2

flutter: