name: submission
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1
  firebase_storage: ^11.2.5
  custom_date_range_picker: ^1.0.10
  image_picker: ^1.0.1
  flutter_advanced_drawer: ^1.3.5
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.5.0
  confirm_dialog: ^1.0.2
  skeleton_loader: ^2.0.0+4
  flutter_easyloading: ^3.0.5
  cloud_firestore: ^4.8.3
  get: ^4.6.5
  hive: ^2.2.3
  hive_generator: ^2.0.0
  supercharged: ^2.1.1
  flutter_native_image: ^0.0.6
  provider: ^6.0.5
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/illustrations/